config/routes.rb
Tenisowo::Application.routes.draw do |map|
  devise_for :users
    
  root :to => "home#index"
    
  resource :profile
    
  map.connect "match_requests/:id/deny", {:controller => "match_requests", :action => "deny", :id => /[1-9]+[0-9]*/}
  map.connect "match_requests/:id/cancel", {:controller => "match_requests", :action => "cancel", :id => /[1-9]+[0-9]*/}
    
  map.connect "match_requests/:id/edit_deny", {:controller => "match_requests", :action => "edit_deny", :id => /[1-9]+[0-9]*/}
    
  map.connect "matches/:id/accept", {:controller => "matches", :action => "accept", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/edit_accept", {:controller => "matches", :action => "edit_accept", :id => /[1-9]+[0-9]*/}  
  
  map.connect "matches/:id/deny", {:controller => "matches", :action => "deny", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/edit_deny", {:controller => "matches", :action => "edit_deny", :id => /[1-9]+[0-9]*/}
    
  map.connect "matches/:id/ignore", {:controller => "matches", :action => "ignore", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/stop_ignoring", {:controller => "matches", :action => "stop_ignoring", :id => /[1-9]+[0-9]*/}  
  
  resources :match_requests do
    resources :messages
  end
    
  resources :matches do
    resources :messages
    resources :rates
  end
  
  resources :messages
  
  resources :players do
    resources :match_requests
    resources :matches
  end
    
  namespace :user do
    root :to => "home#index"
  end

end

app/models/match_request.rb
class MatchRequest < ActiveRecord::Base
  default_scope :order => "created_at DESC"
  
  scope :active, :conditions => {:denied => false, :cancelled => false, :accepted => false}
  scope :denied, :conditions => {:denied => true, :cancelled => false, :accepted => false}
  scope :accepted, :conditions => {:denied => false, :cancelled => false, :accepted => true}
    
  scope :not_denied,
    lambda {|player|  
      {:conditions => ["(second_player_id = ? and denied = ?) or owner_id = ?", player.id, false, player.id]}}      
  scope :not_cancelled, :conditions => {:cancelled => false}

  scope :with_match_request,
    lambda {|player|  
      {:conditions => ["owner_id = ? or second_player_id = ?", player.id, player.id]}}
 
  belongs_to :owner, :class_name => "Profile"
  belongs_to :second_player, :class_name => "Profile"
  
  belongs_to :match
  
  has_many :messages

  HUMANIZED_ATTRIBUTES = {
    :why_denied => 'Pole "Powód"',
    :description => 'Pole "Wiadomość"'
  }
  
  def self.human_attribute_name(attr, options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
  
  
  validates_presence_of :owner_id, :second_player_id, :description, :message => "nie może być puste!"
  
	def opponent(player)
    if player.id == owner_id
      return second_player
    else
      return owner
    end
  end
  
  def is_active
    !denied and !cancelled and !accepted
  end
  
end

app/controllers/admin/match_requests_controller.rb
class Admin::MatchRequestsController < Admin::ResourcesController
end

app/controllers/match_requests_controller.rb
class MatchRequestsController < ApplicationController
  layout "logged"

  before_filter :authenticate_user!
  before_filter :check_profile!
  before_filter :get_last_matches!


  before_filter do
    @match_requests_controller = "current_page_item"
  end

  def index
    @owner = true
    if params[:type]
      if params[:type] == "received"
        @title = "recieved"
        @match_requests = @profile.other_match_requests.active.paginate :page => params[:page], :per_page => per_page
        @owner = false
      else
        if params[:type] == "sent"
          @title = "sent"
          @match_requests = @profile.owned_match_requests.active.paginate :page => params[:page], :per_page => per_page
        else
          if params[:type] == "accepted"
            @title = "accepted"
            @match_requests = @profile.match_requests.accepted.paginate :page => params[:page], :per_page => per_page
          else
            @title = "rejected"
            @match_requests = @profile.match_requests.denied.paginate :page => params[:page], :per_page => per_page
          end
        end
      end
      #@ignored = @matches.ignored(player)
      #@played = @matches.not_ignored(player).played
      #@not_played = @matches.not_ignored(player).not_played
    else
      @title = "recieved"
      @match_requests = @profile.other_match_requests.active.paginate :page => params[:page], :per_page => per_page
      @owner = false
    end
  end

  def show
    @match_request = @profile.match_requests.find(params[:id])
    @owner = @match_request.owner

    if @profile == @match_request.owner
      @is_owner = true
    else
      @is_owner = false
    end

    @message = @match_request.messages.new
    @messages = @match_request.messages.all
  end

  def create
    @player = Profile.find(params[:player_id])
    @match_request = @player.other_match_requests.new(params[:match_request])
    @match_request.owner = @profile

    if @match_request.owner == @match_request.second_player
      flash[:error] = "You cannot play with yourself"

      redirect_to player_path(@player)
      return
    end

    if @match_request.save
      redirect_to match_request_path(@match_request)
    else
      @match_requests_controller = ""
      @players_controller = "current_page_item"
      render "players/show"
    end
  end

  def edit_deny
    @match_request = @profile.other_match_requests.find(params[:id])

    if !@match_request.is_active
      flash[:error] = "You cannot reject this offer"
      redirect_to match_request_path(@match_request)

      return
    end

    render 'edit_deny'
  end

  def deny
    @match_request = @profile.other_match_requests.find(params[:id])

    if !@match_request.is_active
      flash[:error] = "You cannot reject this offer"
      redirect_to match_request_path(@match_request)

      return
    end

    if params[:match_request][:why_denied] == ""
      @match_request.errors.add_to_base 'Reason this cannot be empty'
      render 'edit_deny'

      return
    end

    @match_request.denied = true

    if @match_request.update_attributes(params[:match_request])
      @match_request.save

      redirect_to match_requests_path
    else

      render 'edit_deny'
    end
  end

  def cancel
    @match_request = @profile.owned_match_requests.find(params[:id])

    if @match_request.accepted or @match_request.denied or @match_request.cancelled
      flash[:error] = "You cannot cancel this offer"
      redirect_to match_request_path(@match_request)

      return
    end

    @match_request.cancelled = true
    @match_request.save

    redirect_to match_requests_path
  end

end

app/views/match_requests/_menu.html.haml
- content_for :extra do
  %li
    %h2 Latest Offers
    %ul
      %li= link_to "Recieved", match_requests_path + "?type=received"
      %li= link_to "Reviewing", match_requests_path + "?type=sent"
      %li= link_to "Accepted", match_requests_path + "?type=accepted"
      %li= link_to "Rejected", match_requests_path + "?type=denied"

app/views/match_requests/_messages.html.haml
.post
  %h2.title Messeges
  %p
  .entry
    .scroll
      - messages.each do |m|
        %b
          = m.content
        %br
        %b
          = m.author.nick + ","
        = m.created_at.to_time
        %hr
    %p
    %h3
      =link_to "New Messege", new_match_request_message_path(match_request)

app/views/match_requests/edit_deny.html.haml
= render :partial => "shared/object_errors", :locals => {:object => @match_request}

.post
  %h2.title Rejected
  .entry
    %p
      - form_for @match_request, :url => {:action => "deny"} do |f|
        %table
          %tr
            %th Reason:
            %td
              = f.text_area :why_denied
          %tr
            %td
            %td
              =f.submit "OK"

app/views/match_requests/index.html.haml
= render :partial => "menu"

.post
  %h2.title= @title
  %p
  .entry
    %table.bordered
      %tr
        %th Opponant
        %th
      - @match_requests.each do |r|
        %tr
          %td
            =r.opponent(@profile).nick
          %td
            = link_to "More", match_request_path(r)
    %br
    = will_paginate @match_requests

app/views/match_requests/show.html.haml
- if @match_request.denied
  .notice
    %p.bold
      Offer rejected, reason:
    %p= @match_request.why_denied

- if @match_request.cancelled
  .notice
    %p.bold Offer cancelled.


- if @match_request.accepted
  .notice
    %p.bold
      Offer accepted.
    %p
      New match has been created.
      = link_to "View.", match_path(@match_request.match)

.post
  %h2.title
    - if @is_owner
      Dla:
      =link_to @match_request.second_player.nick, player_path(@match_request.second_player)
    - else
      Od:
      =link_to @match_request.owner.nick, player_path(@match_request.owner)
  %p
  .entry
    .little_scroll
      = @match_request.description

    - if @match_request.is_active and !@is_owner
      %p
      %h3.centered
        = link_to "Accept", matches_path(:id => @match_request.id), :method => :post
        |
        = link_to "Reject", :action => "edit_deny"


= render :partial => "messages", :locals => {:messages => @messages, :match_request => @match_request}


- if @is_owner and !@match_request.accepted and !@match_request.denied and !@match_request.cancelled
  %h3
    = link_to "Cancel Offer", {:action => "cancel"}, :confirm => "Are you sure?"

= render :partial => "menu"