config/routes.rb
Tenisowo::Application.routes.draw do |map|
  devise_for :users
    
  root :to => "home#index"
    
  resource :profile
    
  map.connect "match_requests/:id/deny", {:controller => "match_requests", :action => "deny", :id => /[1-9]+[0-9]*/}
  map.connect "match_requests/:id/cancel", {:controller => "match_requests", :action => "cancel", :id => /[1-9]+[0-9]*/}
    
  map.connect "match_requests/:id/edit_deny", {:controller => "match_requests", :action => "edit_deny", :id => /[1-9]+[0-9]*/}
    
  map.connect "matches/:id/accept", {:controller => "matches", :action => "accept", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/edit_accept", {:controller => "matches", :action => "edit_accept", :id => /[1-9]+[0-9]*/}  
  
  map.connect "matches/:id/deny", {:controller => "matches", :action => "deny", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/edit_deny", {:controller => "matches", :action => "edit_deny", :id => /[1-9]+[0-9]*/}
    
  map.connect "matches/:id/ignore", {:controller => "matches", :action => "ignore", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/stop_ignoring", {:controller => "matches", :action => "stop_ignoring", :id => /[1-9]+[0-9]*/}  
  
  resources :match_requests do
    resources :messages
  end
    
  resources :matches do
    resources :messages
    resources :rates
  end
  
  resources :messages
  
  resources :players do
    resources :match_requests
    resources :matches
  end
    
  namespace :user do
    root :to => "home#index"
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  layout "logged"
  
  before_filter :authenticate_user!
  before_filter :check_profile!
  before_filter :get_last_matches!
  
  before_filter do
    @players_controller = "current_page_item"
  end
  
  def index
    @search = Profile.where("user_id != ?", current_user.id).search(params[:search])
    @players = @search.all(:conditions => ["nick is not null and active = ?", true]).paginate :page => params[:page], :per_page => per_page
  end
  
  def show
    @player = Profile.find(params[:id], :conditions => "nick is not null")
    
    @match_request = @player.other_match_requests.new
  end
end

app/views/players/index.html.haml
.post
  %h2.title Other Players
  %p
  .entry
    %table.bordered
      %tr
        %th Nick
        %th State
        %th City
        %th NTRP
        %th
      - @players.each do |player|
        %tr
          %td= player.nick
          %td= player.state
          %td= player.city
          %td= player.ntrp
          %td= link_to "more", player_path(player)
    %br
    = will_paginate @match_requests
- content_for :extra do
  %li
    #search
      %h2 Search for players
      = form_for @search, :url => players_path, :html => {:method => :get} do |f|
        %table
          %tr
            %td
              Name:
            %td
              =f.text_field :nick_contains, :class => "short"
          %tr
            %td
              City:
            %td
              = f.text_field :city_contains, :class => "short"
          %tr
            %td
              State:
            %td
              = f.text_field :state_contains, :class => "short"
          %tr
            %td NTRP:
            %td
              = f.select :ntrp_gteq, [[1.0, 1.0], [1.5, 1.5], [2.0, 2.0], [2.5, 2.5], [3.0, 3.0], [3.5, 3.5], [4.0, 4.0], [4.5, 4.5], [5.0, 5.0], [5.5, 5.5], [6.0, 6.0], [6.5, 6.5], [7.0, 7.0]], :selected => 1.0
              = "-"
              = f.select :ntrp_lteq, [[1.0, 1.0], [1.5, 1.5], [2.0, 2.0], [2.5, 2.5], [3.0, 3.0], [3.5, 3.5], [4.0, 4.0], [4.5, 4.5], [5.0, 5.0], [5.5, 5.5], [6.0, 6.0], [6.5, 6.5], [7.0, 7.0]], :selected => 7.0
          %tr
            %td
            %td
              = f.submit :Search
    .clear

app/views/players/show.html.haml
= render :partial => "shared/object_errors", :locals => {:object => @match_request}
.post
  %h2.title= @player.nick
  %p
  .entry
    %table.bordered
      %tr
        %th Name
        %th Surname
        %th Email
        %th State
        %th City
        %th NTRP
      %tr
        %td
          - if @player.hide_name
            Ukryte
          - else
            = @player.first_name
        %td
          - if @player.hide_name
            Ukryte
          - else
            = @player.last_name
        %td= @player.email
        %td= @player.state
        %td= @player.city
        %td= @player.ntrp

.post
  %h2.title Ratings
  %p
  .entry
    %table.bordered
      %tr
        %th Positive
        %th Neutral
        %th Negative
        %th Percent Positive
      %tr
        %td= @player.owned_rates.positive.count
        %td= @player.owned_rates.neutral.count
        %td= @player.owned_rates.negative.count
        %td
          - if @player.owned_rates.all.count == 0
            No Ratings
          - else
            = (@player.owned_rates.positive.count / @player.owned_rates.all.count) * 100
    %p
    %h3 More

.post
  %h2.title Challenge this player to a match
  %p
  .entry
    - form_for [@player, @match_request], :url => player_match_requests_path(@player) do |f|
      %table
        %tr
          %th Messege:
          %td
            = f.text_area :description
        %tr
          %td
          %td
            = f.submit "Send"