config/routes.rb
Tenisowo::Application.routes.draw do |map|
  devise_for :users
    
  root :to => "home#index"
    
  resource :profile
    
  map.connect "match_requests/:id/deny", {:controller => "match_requests", :action => "deny", :id => /[1-9]+[0-9]*/}
  map.connect "match_requests/:id/cancel", {:controller => "match_requests", :action => "cancel", :id => /[1-9]+[0-9]*/}
    
  map.connect "match_requests/:id/edit_deny", {:controller => "match_requests", :action => "edit_deny", :id => /[1-9]+[0-9]*/}
    
  map.connect "matches/:id/accept", {:controller => "matches", :action => "accept", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/edit_accept", {:controller => "matches", :action => "edit_accept", :id => /[1-9]+[0-9]*/}  
  
  map.connect "matches/:id/deny", {:controller => "matches", :action => "deny", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/edit_deny", {:controller => "matches", :action => "edit_deny", :id => /[1-9]+[0-9]*/}
    
  map.connect "matches/:id/ignore", {:controller => "matches", :action => "ignore", :id => /[1-9]+[0-9]*/}
  map.connect "matches/:id/stop_ignoring", {:controller => "matches", :action => "stop_ignoring", :id => /[1-9]+[0-9]*/}  
  
  resources :match_requests do
    resources :messages
  end
    
  resources :matches do
    resources :messages
    resources :rates
  end
  
  resources :messages
  
  resources :players do
    resources :match_requests
    resources :matches
  end
    
  namespace :user do
    root :to => "home#index"
  end

end

app/models/match.rb
class Match < ActiveRecord::Base
  
  
  
  default_scope :order => "created_at DESC"
  
  belongs_to :owner, :class_name => "Profile"
  belongs_to :first_player, :class_name => "Profile"
  belongs_to :second_player, :class_name => "Profile"
  belongs_to :winner, :class_name => "Profile"
  
  
  
  has_one :match_request
  
  scope :active, :conditions => {:cancelled => false}
  scope :cancelled, :conditions => {:cancelled => true}
  
  scope :with_matches,
    lambda {|player|  
      {:conditions => ["first_player_id = ? or second_player_id = ?", player.id, player.id]}}
  
  scope :played, :conditions => {:was_played => true}
  scope :not_played, :conditions => {:was_played => false}
  
  scope :not_ignored, 
    lambda {|player|  
      {:conditions => ["(first_player_id = ? and first_player_ignores = ?) or (second_player_id = ? and second_player_ignores = ?)", player.id, false, player.id, false]}}
  
  scope :ignored, 
    lambda {|player|  
      {:conditions => ["(first_player_id = ? and first_player_ignores = ?) or (second_player_id = ? and second_player_ignores = ?)", player.id, true, player.id, true]}}
  
  
  has_many :messages
  
  has_many :rates

  validates_presence_of :owner_id, :first_player_id, :second_player_id, :message => "nie może być puste"

    
  def opponent(player)
    if player.id == first_player_id
      return second_player
    else
      return first_player
    end
  end
  
  def is_ignored(player)
    if player.id == first_player_id
      return first_player_ignores
    else
      return second_player_ignores
    end
  end  
  
  def is_rated(player)
    if player.id == first_player_id
      return is_rated_by_first_player
    else
      return is_rated_by_second_player
    end
  end
  
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < Admin::ResourcesController
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  layout "logged"

  before_filter do
    @matches_controller = "current_page_item"
  end

  before_filter :authenticate_user!
  before_filter :check_profile!
  before_filter :get_last_matches!

  def index

    if params[:type]
      case params[:type]
      when "not_played" then
        @title = "not played"
        @matches = @profile.matches.active.not_ignored(@profile).not_played.paginate :page => params[:page], :per_page => per_page
      when "played"
        @title = "played"
        @matches = @profile.matches.active.not_ignored(@profile).played.paginate :page => params[:page], :per_page => per_page
      when "ignored"
        @title = "ignored"
        @matches = @profile.matches.active.ignored(@profile).paginate :page => params[:page], :per_page => per_page
      else
        @title = "cancelled"
        @matches = @profile.matches.cancelled.paginate :page => params[:page], :per_page => per_page
      end
    else
      @title = "unmatched"
      @matches = @profile.matches.active.not_ignored(@profile).not_played.paginate :page => params[:page], :per_page => per_page
    end

  end

  def show
    @match = @profile.matches.find(params[:id])
    @rate = @match.rates.new
    @messages = @match.messages.all

    if @match.first_player == @profile
      @is_rated = @match.is_rated_by_first_player
    else
      @is_rated = @match.is_rated_by_second_player
    end

    if @match.cancelled
      render 'show_cancelled'

      return
    end

    if @match.is_ignored(@profile)
      render 'show_ignored'

      return
    end

    if !@match.was_played
      if @match.owner == @profile
        render 'provide_info'
      else
        render 'accept'
      end
    end
  end

  def create
    @match_request = @profile.other_match_requests.find(params[:id])
    @messages = @match_request.messages.all

    if !@match_request.is_active
      flash[:error] = "You cannot accept this offer."

      redirect_to match_request_path(@match_request)
      return
    end

    @owner = @match_request.owner

    @match = @owner.owned_matches.new
    @match.first_player = @owner
    @match.second_player = @profile

    if @match.first_player == @match.second_player
      flash[:error] = "Cannot play against yourself."

      redirect_to match_request_path(@match_request)
      return
    end

    @match.messages = @messages

    if @match.save
      @match_request.accepted = true
      @match_request.match = @match
      @match_request.save
      redirect_to match_path(@match)
    else
      flash[:error] = "Cannot accept this offer"
      redirect_to match_request_path(@match_request)
    end
  end

  def update
    @match = @profile.owned_matches.find(params[:id])

    if @match.is_ignored(@profile) or @match.was_played or @match.info_provided or @match.cancelled
      flash[:error] = "You cannot update the data for this match"
      redirect_to match_path(@match)

      return
    end

    if (params[:match][:where] == "" or params[:match][:when] == "")
      flash[:error] = "The result cannot be empty"
      redirect_to match_path(@match)

      return
    end

    if @match.update_attributes(params[:match])
      @match.info_provided = true
      @match.save
      redirect_to match_path(@match)
    else
      flash[:error] = "You cannot accept this offer"
      redirect_to match_path(@match)
    end
  end

  def edit_accept
    @match = @profile.matches_as_second_player.find(params[:id])

    if @match.is_ignored(@profile) or @match.was_played or !@match.info_provided or @match.cancelled
      flash[:error] = "You cannot accept this match"
      redirect_to match_path(@match)

      return
    end

    render 'edit_accept'
  end

  def edit_deny
    @match = @profile.matches_as_second_player.find(params[:id])

    if @match.is_ignored(@profile) or @match.was_played or !@match.info_provided or @match.cancelled
      flash[:error] = "You cannot accept this match"
      redirect_to match_path(@match)

      return
    end

    render 'edit_deny'
  end

  def accept
    @match = @profile.matches_as_second_player.find(params[:id])

    if @match.is_ignored(@profile) or @match.was_played or !@match.info_provided or @match.cancelled
      flash[:error] = "You cannot accept this match"
      redirect_to match_path(@match)

      return
    end

    @match.second_players_description = params[:match][:second_players_description]
    @match.was_played = true
    @match.save

    redirect_to match_path(@match)
  end

  def deny
    @match = @profile.matches_as_second_player.find(params[:id])

    if @match.is_ignored(@profile) or @match.was_played or !@match.info_provided or @match.cancelled
      flash[:error] = "You cannot accept this match"
      redirect_to match_path(@match)

      return
    end

    if (params[:match][:why_denied] == "")
      @match.errors.add_to_base("No reason given")
      render 'edit_deny'
      return
    end

    @match.info_denied = true
    @match.why_denied = params[:match][:why_denied]
    @match.info_provided = false
    @match.save

    redirect_to match_path(@match)
  end

  def ignore
    @match = @profile.matches.find(params[:id])

    if @match.is_ignored(@profile) or @match.was_played or @match.cancelled
      flash[:error] = "Match has already started"
      redirect_to match_path(@match)

      return
    end

    if @profile == @match.first_player
      @match.first_player_ignores = true
    else
      @match.second_player_ignores = true
    end

    @match.save
    redirect_to match_path(@match)
  end

  def stop_ignoring
    @match = @profile.matches.ignored(@profile).find(params[:id])

    if !@match.is_ignored(@profile) or @match.cancelled
      flash[:error] = "Match has already started"
      redirect_to match_path(@match)

      return
    end


    if @profile == @match.first_player
      @match.first_player_ignores = false
    else
      @match.second_player_ignores = false
    end
    @match.save
    redirect_to match_path(@match)
  end
end

app/views/matches/_match_info.html.haml
.post
  %h2.title= match.first_player.nick + " vs " + match.second_player.nick
  %p
  .entry
    %p
      Match info.

app/views/matches/_menu.html.haml
- content_for :extra do
  %li
    %h2 Matches
    %ul
      %li= link_to "Unmatched", matches_path + "?type=not_played"
      %li= link_to "Played", matches_path + "?type=played"
      %li= link_to "Ignored", matches_path + "?type=ignored"
      %li= link_to "Cancelled", matches_path + "?type=cancelled"

app/views/matches/_messages.html.haml
.post
  %h2.title Wiadomości
  %p
  .entry
    .scroll
      - messages.each do |m|
        %b
          = m.content
        %br
        %b
          = m.author.nick + ","
        = m.created_at.to_time
        %hr
    %p
    %h3
      =link_to "Nowa wiadomość", new_match_message_path(match)

app/views/matches/_players.html.haml
%h2.title
  = link_to match.first_player.nick, player_path(match.first_player)
  = "-"
  = link_to match.second_player.nick, player_path(match.second_player)

app/views/matches/_rate.html.haml
-if !is_rated
  .post
    %h2.title Oceń przeciwnika
    %p
    .entry
      - form_for [match, rate] do |f|
        %table
          %tr
            %th Twoja ocena:
            %td
              Pozytywna
              = f.radio_button :rate_value, 1, :checked => true
            %td
              Neutralna
              = f.radio_button :rate_value, 2
            %td
              Negatywna
              = f.radio_button :rate_value, 3
          %tr
            %th Uzasadnienie:
            %td{:colspan => 3}
              = f.text_area :description, :class => "wide"
          %tr
            %td
            %td{:colspan => 3}
              = f.submit "OK"
-else
  %h3 Przeciwnik został już oceniony
  %p

app/views/matches/accept.html.haml
.post
  = render :partial => "players", :locals => {:match => @match}
  %p
  .entry
    - if @match.info_provided
      %h3 Dane wprowadzone przez drugiego gracza:
      %br
      %table.bordered
        %tr
          %th 
            Zwycięzca:
          %td
            - if @match.winner_id == -1
              Brak zwycięzcy
            - else
              = @match.winner.nick
        %tr
          %th
            Wynik:
          %td
            = @match.score
        %tr
          %th
            Data rozegrania meczu:
          %td
            = @match.when
        %tr
          %th
            Miejsce rozegrania meczu:
          %td
            = @match.where
        %tr
          %th
            Opis pierwszego gracza:
          %td
            - if @match.first_players_description
              = @match.first_players_description
            - else
              = ""
      %p
      %h3.centered
        = link_to "Akceptacja", :action => 'edit_accept'
        |
        = link_to "Odrzucenie", :action => 'edit_deny'
    
    - else
      - if @match.info_denied
        %h3 Odrzuciłeś podane przez drugiego gracza dane. Musisz poczekać na ich ponowne wprowadzenie.
      - else
        %h3 Musisz poczekać na wprowadzenie danych przez drugiego gracza.

    

= render :partial => "messages", :locals => {:messages => @messages, :match => @match}

= render :partial => "rate", :locals => {:match => @match, :rate => @rate, :is_rated => @is_rated}

%h3= link_to "Dodaj mecz do ignorowanych", {:action => 'ignore'}

= render :partial => "menu"

app/views/matches/edit_accept.html.haml
.post
  %h2.title Akceptacja wprowadzonych wyników
  .entry
    %p
      - form_for @match, :url => {:action => "accept"} do |f|
        %table
          %tr
            %th Twój opis meczu
            %td
              = f.text_area :second_players_description
          %tr
            %td
            %td
              =f.submit "OK"

app/views/matches/edit_deny.html.haml
= render :partial => "shared/object_errors", :locals => {:object => @match}


.post
  %h2.title Odrzucenie wprowadzonych wyników
  .entry
    %p
      - form_for @match, :url => {:action => "deny"} do |f|
        %table
          %tr
            %th Powód:
            %td
              = f.text_area :why_denied
          %tr
            %td
            %td
              =f.submit "OK"

app/views/matches/index.html.haml
= render :partial => "menu"

.post
  %h2.title= @title
  %p
  .entry
    %table.bordered
      %tr
        %th Przeciwnik
        %th
      - @matches.each do |m|
        %tr
          %td
            = m.opponent(@profile).nick
          %td
            = link_to "Więcej", match_path(m)
    %br
    = will_paginate @matches

app/views/matches/provide_info.html.haml
- if @match.info_denied
  .notice
    %p.bold
      Odrzucono wprowadzone dane. Powód:
    %p= @match.why_denied

.post
  = render :partial => "players", :locals => {:match => @match}
  %p
  .entry
    - form_for @match do |f|
      %table
        %tr
          %th 
            Wybierz zwycięzcę:
          %td
            = f.select :winner_id, [[@match.first_player.nick, @match.first_player.id], [@match.second_player.nick, @match.second_player.id], ["Brak zwycięzcy", -1]]
        %tr
          %th
            Podaj wynik:
          %td
            = f.text_field :score
        %tr
          %th
            Data rozegrania meczu:
          %td
            = f.date_select :when, :use_month_numbers => true
        %tr
          %th
            Miejsce rozegrania meczu:
          %td
            = f.text_field :where
        %tr
          %th
            Twój opis meczu:
          %td
            = f.text_area :first_players_description, :class => "wide"
        %tr
          %td
          %td
            - if !@match.info_provided
              = f.submit "OK"
            - else
              %p Wprowadzone dane oczekują na akceptację drugiego gracza



= render :partial => "messages", :locals => {:messages => @messages, :match => @match}

= render :partial => "rate", :locals => {:match => @match, :rate => @rate, :is_rated => @is_rated}

%h3= link_to "Dodaj mecz do ignorowanych", {:action => 'ignore'}

= render :partial => "menu"    

app/views/matches/show.html.haml
.post
  = render :partial => "players", :locals => {:match => @match}
  %p
  .entry
    %p
      %table.bordered
        %tr
          %th 
            Zwycięzca:
          %td
            - if @match.winner_id == -1
              Brak zwycięzcy
            - else
              = @match.winner.nick
        %tr
          %th
            Wynik:
          %td
            = @match.score
        %tr
          %th
            Data:
          %td
            = @match.when
        %tr
          %th
            Miejsce:
          %td
            = @match.where
        %tr
          %th
            Opis pierwszego gracza:
          %td
            - if @match.first_players_description
              = @match.first_players_description
            - else
              = ""
        %tr
          %th
            Opis drugiego gracza:
          %td
            - if @match.second_players_description
              = @match.second_players_description
            - else
              = ""
              
= render :partial => "messages", :locals => {:messages => @messages, :match => @match}

= render :partial => "rate", :locals => {:match => @match, :rate => @rate, :is_rated => @is_rated}

= render :partial => "menu"

app/views/matches/show_cancelled.html.haml
.post
  = render :partial => "players", :locals => {:match => @match}
  %p
  .entry
    %p.notice
      Konto przeciwnika zostało usunięte
      

= render :partial => "menu"

app/views/matches/show_ignored.html.haml
.post
  = render :partial => "players", :locals => {:match => @match}
  %p
  .entry
    %p
      %h3 
        Mecz jest ignorowany.
        =link_to "Przestań ignorować", :action => 'stop_ignoring'


= render :partial => "messages", :locals => {:messages => @messages, :match => @match}
= render :partial => "rate", :locals => {:match => @match, :rate => @rate, :is_rated => @is_rated}
          
= render :partial => "menu"